RANDOMLY RECEIVED THIS ERROR
LiIon batts and Uno PWR jack NOT PLUGGED IN!

Command received (Start): $0

Down-facing photo capture started.
Down-facing photo capture finished.
Up-facing photo capture started.
Up-facing photo capture finished.
PiCam photo capture started.
PiCam photo capture finished.

Command received (Main): $1

Entering takeoff capture.
Down-facing video capture started.
Up-facing photo capture started.
Up-facing photo capture finished.
PiCam photo capture started.
PiCam photo capture finished.
Traceback (most recent call last):
  File "./hab_camcontrol.py", line 174, in <module>
    if habSerial.inWaiting() > 0:
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
IOError: [Errno 5] Input/output error


WHEN TRYING TO RESTART PROGRAM RECEIVED THIS

Traceback (most recent call last):
  File "./hab_camcontrol.py", line 11, in <module>
    habSerial = serial.Serial('/dev/ttyACM0', 115200, timeout=1)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'